### Removes stop words from abstracts

In [18]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pandas as pd

In [32]:
# import raw data csv from top journals, other high ranking journals, & not high rank journals
topJourns_df = pd.read_csv("raw_data_econ/topJournals_abstract.csv", encoding = "'iso-8859-1'")
hiJourns_df = pd.read_csv("raw_data_econ/hiRankJournals_abstract.csv", encoding = "'iso-8859-1'")
notHiJourns_df = pd.read_csv("raw_data_econ/notHiJournals_abstract.csv", encoding = "'iso-8859-1'")
notHiJourns_df.tail()

,Unnamed: 0,abstract,top_journal
1331,1331,This essay presents a microeconomic model of a...,0
1332,1332,One of the most substantial and challenging po...,0
1333,1333,Transcendental realism criticises the predomin...,0
1334,1334,This paper is a critical examination of Tony L...,0
1335,1335,"Economics, as much as critical realism, is par...",0

In [41]:
# Cleaning stop words 
stop_words = set(stopwords.words('english'))
def clean_stop_words(df):
    for index, row in df.iterrows():
        word_tokens = word_tokenize(row["abstract"])
        filtered_sentence = []
        for w in word_tokens:
            if w not in stop_words:
                filtered_sentence.append(w)
        string = ' '.join(filtered_sentence)
        df.set_value(index, "abstract", string)
    return df

top_cleaned = clean_stop_words(topJourns_df)
top_cleaned.tail()

,Unnamed: 0,abstract,top_journal
2193,2193,We study managerâemployee interactions exper...,1
2194,2194,"In article explore proposition , economies imp...",1
2195,2195,Business cycles less volatile synchronized wor...,1
2196,2196,"From end second century CE , Judaism enforced ...",1
2197,2197,Conventional economic analyses successful expl...,1

In [42]:
# cleaning other high ranking and not high rank journals
hi_cleaned = clean_stop_words(hiJourns_df)

notHi_cleaned = clean_stop_words(notHiJourns_df)

notHi_cleaned.tail()

,Unnamed: 0,abstract,top_journal
1331,1331,This essay presents microeconomic model servic...,0
1332,1332,One substantial challenging post-positivist me...,0
1333,1333,Transcendental realism criticises predominant ...,0
1334,1334,This paper critical examination Tony Lawson ? ...,0
1335,1335,"Economics , much critical realism , part Enlar...",0

In [44]:
# save all cleaned to csv
top_cleaned.to_csv('raw_data_econ/topRanks_cleaned.csv', index=False)
hi_cleaned.to_csv('raw_data_econ/hiRanks_cleaned.csv', index=False)
notHi_cleaned.to_csv('raw_data_econ/notHiRanks_cleaned.csv', index=False)